Set tag to Windows Docker image
VirtoCommerce/vc-docker pull request #4
Opened 2020-05-12 14:04 UTC by joostmeijles

The storefront latest points to a Linux image use the `dev-branch` Windows version instead.

2020-05-12 14:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/VirtoCommerce/vc-docker?pullRequest=4) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/VirtoCommerce/vc-docker?pullRequest=4) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/VirtoCommerce/vc-docker?pullRequest=4) it.</sub>

2020-05-12 14:13 UTC, joostmeijles commented
Not sure if this combination of images should work. I am getting authorization errors on the storefront:

```
vc-storefront-web_1  | Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
vc-storefront-web_1  |    at VirtoCommerce.Storefront.AutoRestClients.StoreModuleApi.StoreModule.GetStoresWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken) in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\AutoRestClients\StoreModuleApi.cs:line 669
vc-storefront-web_1  |    at VirtoCommerce.Storefront.AutoRestClients.StoreModuleApi.StoreModuleExtensions.GetStoresAsync(IStoreModule operations, CancellationToken cancellationToken) in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\AutoRestClients\StoreModuleApi.cs:line 1946
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__7_0(MemoryCacheEntryOptions cacheEntry) in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 53
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync[TItem](IMemoryCache cache, String key, Func`2 factory, Boolean cacheNullValue)
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 48
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, String defaultStoreId) in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreWorkContextBuilderExtensions.cs:line 51
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in S:\Builds\VirtoCommerce\vc-storefront-core\dev\workspace\VirtoCommerce.Storefront\Middleware\WorkContextBuildMiddleware.cs:line 60
vc-storefront-web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
vc-storefront-web_1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
vc-storefront-web_1  | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
vc-storefront-web_1  |       Request finished in 29.4536ms 500
```

2020-05-12 14:38 UTC, lnetrebskii commented
Review task https://virtocommerce.atlassian.net/browse/VP-2288 has been created

2020-05-14 08:01 UTC, mvktsk requested changes
Unfortunately we have published wrong `virtocommerce/storefront:latest` image.
Image `virtocommerce/storefront:latest` should based on Windows image.
We will republish `virtocommerce/storefront:latest` image soon.

As a temporary solution, you can use `virtocommerce/storefront:dev-branch` image

Thank you for your PR.

2020-05-14 08:04 UTC, joostmeijles commented
@mvktsk thanks for the update. Unfortunately I get with the `dev-branch` the mentioned error (https://github.com/VirtoCommerce/vc-docker/pull/4#issuecomment-627372337). How do I solve that one?

2020-05-14 08:51 UTC, mvktsk commented
> @mvktsk thanks for the update. Unfortunately I get with the `dev-branch` the mentioned error ([#4 (comment)](https://github.com/VirtoCommerce/vc-docker/pull/4#issuecomment-627372337)). How do I solve that one?

@joostmeijles 
We have updated `virtocommerce/storefront:latest` recently. 
Try to use this one.
https://hub.docker.com/r/virtocommerce/storefront/tags

2020-05-14 09:56 UTC, joostmeijles commented
With the latest I also get authorization errors:
```
vc-storefront-web_1  | fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
vc-storefront-web_1  |       An unhandled exception has occurred while executing the request.
vc-storefront-web_1  | Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'Unauthorized'
vc-storefront-web_1  |    at VirtoCommerce.Storefront.AutoRestClients.StoreModuleApi.StoreModule.GetStoresWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken) in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\AutoRestClients\StoreModuleApi.cs:line 669
vc-storefront-web_1  |    at VirtoCommerce.Storefront.AutoRestClients.StoreModuleApi.StoreModuleExtensions.GetStoresAsync(IStoreModule operations, CancellationToken cancellationToken) in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\AutoRestClients\StoreModuleApi.cs:line 1946
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreService.<GetAllStoresAsync>b__7_0(MemoryCacheEntryOptions cacheEntry) in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 53
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Model.Common.Caching.MemoryCacheExtensions.GetOrCreateExclusiveAsync[TItem](IMemoryCache cache, String key, Func`2 factory, Boolean cacheNullValue)
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreService.GetAllStoresAsync() in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreService.cs:line 48
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Domain.StoreWorkContextBuilderExtensions.WithStoresAsync(IWorkContextBuilder builder, String defaultStoreId) in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\Domain\Stores\StoreWorkContextBuilderExtensions.cs:line 51
vc-storefront-web_1  |    at VirtoCommerce.Storefront.Middleware.WorkContextBuildMiddleware.Invoke(HttpContext context) in S:\Builds\VirtoCommerce\vc-storefront-core\master\workspace\VirtoCommerce.Storefront\Middleware\WorkContextBuildMiddleware.cs:line 60
vc-storefront-web_1  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
vc-storefront-web_1  |    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
vc-storefront-web_1  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

I tried to add app id and secret keys to the container, but that doesn't help.
```
vc-storefront-web:
    image: virtocommerce/storefront:${DOCKER_TAG:-latest}
    environment:
       - VirtoCommerce:Endpoint:Url=http://vc-platform-web
       - VirtoCommerce:Endpoint:AppId:"27e0d789f12641049bd0e939185b4fd2"
      - VirtoCommerce:Endpoint:SecretKey:"9776e711eeffbd494b326d57301d9e..."
```

2020-05-20 09:43 UTC, mvktsk commented
Hi @joostmeijles,

Sorry for the long answer. It looks like sample data not installed on the platform. We need time to investigate this issue

2020-05-29 03:36 UTC, mvktsk commented
I have  updated docker-compose file in aspnetcore folder https://github.com/VirtoCommerce/vc-docker/tree/master/windows/aspnetcore)
Try to use this docker-compose file.

Next, after the services are started:

1. open platform (http://localhost:8090) and install modules and sample data (Electronics catalog)
2. recreate the search index
3. open storefront (http://localhost:8080)

2020-05-29 03:36 UTC, closed without merging

2020-05-29 08:29 UTC, joostmeijles commented
@mvktsk I keep getting the same `Unauthorized` error.

2020-05-29 15:33 UTC, mvktsk commented
> @mvktsk I still get the same `Unauthorized` error.

Hi @joostmeijles,

We have checked the docker-compose works in our environment (we use the latest version of Docker Desktop)

1. Try to Clean /Purge data in Docker Desktop
2. If that doesn't help try to reset factory defaults
![image](https://user-images.githubusercontent.com/44946644/83276841-687b5d80-a1fb-11ea-8a89-6f063b764fa5.png)

2020-05-30 02:47 UTC, Woland2k commented
@joostmeijles we also just created purely declarative deployments for kubernetes as well as integration with Argo CD. You can see examples of it here: https://cd.govirto.com/.